version: "3.7"
services:
  app:
    build:
      args:
        user: mila
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travel
    container_name: travel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travel

  db:
    image: mysql:latest
    container_name: travel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - travel

  nginx:
    image: nginx:alpine
    container_name: travel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - travel

  dnsmasq:
    image: andyshinn/dnsmasq:latest
    container_name: dnsmasq
    cap_add:
      - NET_ADMIN
    command: --log-queries --log-facility=-
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
networks:
  travel:
    driver: bridge
